### ISSUE TITLE
Normalizar set de tecnologias a partir de la encuesta

### ISSUE THREAD

**Issue by gonzalojavimartin** [gonzalojavimartin/SkillMatchIA#18]
Hacer una pruebita de concepto para extraer de este [dataset de encuesta](https://docs.google.com/spreadsheets/d/1M1SUlDPDZtM1-pGd4GJOTTY7GqHzaEOGbu1DSpVFBeo/edit?gid=1520628801#gid=1520628801) 

- plataformas_que_utilizas_en_tu_puesto_actual	
- lenguajes_de_programacion_o_tecnologias_que_utilices_en_tu_puesto_actual	
- frameworksherramientas_y_librerias_que_utilices_en_tu_puesto_actual	
- bases_de_datos	
- qa_testing

con eso podemos normalizar lenguajes y tecnologías para entrenar mejor al NER

**Comment by AgustinCocciardi** [comment]
Paso la lista de tecnologías que pude extraer del dataset. Es el colab y el csv
[Extraccion_tecnologias.zip](https://github.com/user-attachments/files/17251429/Extraccion_tecnologias.zip)

**Comment by gonzalojavimartin** [comment]
Se crea un script technologies.py en el proyecto, que implementa la lógica de @AgustinCocciardi para generar un array de teconlogias que se importan hacia la constante TECHNOLOGIES del main script
