### ISSUE TITLE
Trasnformar PDF a Texto para procesar CVs

### ISSUE THREAD

**Issue by gonzalojavimartin** [gonzalojavimartin/SkillMatchIA#4]
Ver si existe la posibilidad que la aplicación reciba como adjunto un PDF y pueda pasarlo a texto para luego ser analizado (NLP) para extraer las Skills.
Si llegamos a ver que se complica o no queda bien, el "CV" se subirá como texto en un textarea como está hasta ahora y listo.

**Comment by pecam89** [comment]
[PDFtoText.zip](https://github.com/user-attachments/files/17251166/PDFtoText.zip)

**Comment by AgustinCocciardi** [comment]
No me deja subir el proyecto. Me acuerdo que le instalé un par de librerías, y creo que por eso pesa demasiado. Paso el app.py y el template
[App.py + upload.zip](https://github.com/user-attachments/files/17251188/App.py.%2B.upload.zip)

**Comment by gonzalojavimartin** [comment]
Quedo implementada la extracción de texto desde un PDF y su extracción de tecnologias para luego persistir al candidato
