### ISSUE TITLE
Implementar Chatbot/QA

### ISSUE THREAD

**Issue by gonzalojavimartin** [gonzalojavimartin/SkillMatchIA#5]
Lo que había pensado en este punto es que el chatbot/QA, que en realidad sería como un menú guiado, le "consulte" al usuario que puesto; tecnologias; seniority; o incluso empresa querría aplicar para conocer el sueldo promedio que se maneja en dicho espectro.
Para esto tendríamos que aplicar sobre el dataset de encuesta de sueldos:
- Normalización 
- Categorización
- Algo de ML para "pronosticar" el sueldo

**Comment by pecam89** [comment]
Dejo un enlace con el archivo. Tuve complicaciones con el peso, asi que tuve que crear un enlace a través de una web. Tiene vencimiento el 11/10. De última luego lo vuelvo a crear.

https://we.tl/t-ZIMXhTYWJa

El chatbot lo que haces es lo siguiente:
- Realiza una serie de preguntas al usuario las cuales debe responder.
-Las preguntas que se realizan son respecto a puesto; tecnologias; seniority; ciudad donde le gustaria trabajar y genero. (se pueden agregar otras cosas), según dataset.
- Se despliega una vista general de los datos cargados por el usuario. En paralelo se almancenan en un archivo independiente al dataset para persistir los datos.

**Comment by AgustinCocciardi** [comment]
El tamaño también me quedó enorme. Lo subí al mediafire. 

(https://www.mediafire.com/file/9hltr3xby3gikqf/EncuestaSueldos.zip/file)
